# Generated by Django 5.2.1 on 2025-11-27 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiotipoCutaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuidadoPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('usa_marcapasos', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('historial_clinico', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteBiotipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JyGDreams.biotipocutaneo')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteCuidadoPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(blank=True, max_length=100)),
                ('cuidado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JyGDreams.cuidadopiel')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasos_agua', models.CharField(max_length=100)),
                ('trasnoche', models.CharField(max_length=100)),
                ('tabaco', models.CharField(max_length=100)),
                ('cafe', models.CharField(max_length=100)),
                ('licor', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=100)),
                ('suplementos', models.CharField(max_length=100)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.expediente')),
            ],
        ),
        migrations.AddField(
            model_name='expediente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.paciente'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo_cita', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REPROGRAMADO', 'Reprogramado'), ('REALIZADO', 'Realizado'), ('INASISTENCIA', 'Inasistencia')], default='AGENDADO', max_length=12)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.cita')),
            ],
        ),
        migrations.CreateModel(
            name='CitaProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.cita')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.procedimiento')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='procedimientos',
            field=models.ManyToManyField(through='JyGDreams.CitaProcedimiento', to='JyGDreams.procedimiento'),
        ),
    ]
