# Generated by Django 5.2.1 on 2025-11-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyGDreams', '0002_pago_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='descuento',
        ),
        migrations.AddField(
            model_name='citaprocedimiento',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
