# Generated by Django 5.2.1 on 2025-06-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyGDreams', '0003_procedimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('REPROGRAMADO', 'Reprogramado'), ('REALIZADO', 'Realizado'), ('INASISTENCIA', 'Inasistencia')], default='AGENDADO', max_length=12),
        ),
    ]
