# Generated by Django 5.2.1 on 2026-03-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("JyGDreams", "0003_remove_pago_descuento_citaprocedimiento_descuento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="citas_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

