# Generated by Django 5.2.1 on 2025-06-03 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyGDreams', '0004_alter_cita_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.cita')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.procedimiento')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='procedimientos',
            field=models.ManyToManyField(through='JyGDreams.CitaProcedimiento', to='JyGDreams.procedimiento'),
        ),
    ]
