# Generated by Django 5.2.1 on 2025-06-10 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyGDreams', '0005_citaprocedimiento_cita_procedimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.cita')),
            ],
        ),
    ]
