# Generated by Django 5.2.1 on 2025-06-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyGDreams', '0006_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiotipoCutaneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CuidadoPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('usa_marcapasos', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2)),
                ('historial_clinico', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteBiotipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JyGDreams.biotipocutaneo')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteCuidadoPiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otro', models.CharField(blank=True, max_length=100)),
                ('cuidado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='JyGDreams.cuidadopiel')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasos_agua', models.CharField(max_length=100)),
                ('trasnoche', models.CharField(max_length=100)),
                ('tabaco', models.CharField(max_length=100)),
                ('cafe', models.CharField(max_length=100)),
                ('licor', models.CharField(max_length=100)),
                ('medicamentos', models.CharField(max_length=100)),
                ('suplementos', models.CharField(max_length=100)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.expediente')),
            ],
        ),
    ]
