# Generated by Django 5.2.1 on 2025-05-31 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JyGDreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo_cita', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REPROGRAMADO', 'Reprogramado'), ('REALIZADO', 'Realizado')], default='AGENDADO', max_length=12)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JyGDreams.paciente')),
            ],
        ),
    ]
